export type AuditEvent =
  | "SIGN_IN"
  | "APP_REQUEST_CREATED"
  | "APP_REQUEST_SUCCEEDED"
  | "APP_REQUEST_FAILED"
  | "APP_DELETION_REQUESTED"
  | "APP_DELETION_SUCCEEDED"
  | "APP_DELETION_FAILED"
  | "ARTIFACT_DOWNLOADED"
  | "REPOSITORY_BOOTSTRAP_REQUESTED"
  | "REPOSITORY_BOOTSTRAP_SUCCEEDED"
  | "REPOSITORY_BOOTSTRAP_FAILED"
  | "REPOSITORY_ACCESS_REQUESTED"
  | "REPOSITORY_ACCESS_SUCCEEDED"
  | "REPOSITORY_ACCESS_FAILED"
  | "EXISTING_APP_ADD_REQUESTED"
  | "EXISTING_APP_IMPORT_SUCCEEDED"
  | "EXISTING_APP_IMPORT_FAILED"
  | "REPOSITORY_PREPARATION_COMMITTED"
  | "REPOSITORY_PREPARATION_PR_OPENED"
  | "REPOSITORY_PREPARATION_VERIFIED"
  | "REPOSITORY_PREPARATION_FAILED"
  | "PUBLISH_REQUESTED"
  | "PUBLISH_SUCCEEDED"
  | "PUBLISH_FAILED"
  | "PUSH_TO_DEPLOY_ENABLED";

export async function recordAuditEvent(
  event: AuditEvent,
  details: Record<string, unknown>,
) {
  console.info("[audit]", event, details);
}
